### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaf in position 898: invalid start byte

### ISSUE THREAD

**Issue by sai-33** [aurorayk/New_Hammer#43]
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-useradd'
Traceback (most recent call last):
  File "pyhammer.py", line 864, in goToMain
    main(self.options)
  File "pyhammer.py", line 68, in main
    for i, line in enumerate(infile_init):
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaf in position 898: invalid start byte

**Comment by sai-33** [comment]
![Uploading Screenshot (256).png…]()

**Comment by sai-33** [comment]
![Screenshot (249)](https://user-images.githubusercontent.com/72378635/120895988-15718d00-c63d-11eb-844e-744373037c34.png)

**Comment by zephyr5050** [comment]
This issue is a duplicate of #41. Closing in favor of that ticket.
